//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace mds.BaseModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 配置文件基础（必有）配置项目
	/// </summary>
	public class ComponentConfiguration : DataClassBase
	{
		/// <summary>
		/// 是否进行调试
		/// </summary>
		public virtual bool IsDebug
		{
			get;
			set;
		}

		/// <summary>
		/// 运行环境
		/// </summary>
		public virtual int Environment
		{
			get;
			set;
		}

		public virtual uint ComponentId
		{
			get;
			set;
		}

		public virtual int Version
		{
			get;
			set;
		}

		public virtual string Content
		{
			get;
			set;
		}

		public virtual bool Enable
		{
			get;
			set;
		}

	}
}

