//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace mds.BaseModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class DataClassBase
	{
		public virtual DateTime CreateTime
		{
			get;
			set;
		}

		public virtual DateTime ModifyTime
		{
			get;
			set;
		}

		public virtual bool IsDelete
		{
			get;
			set;
		}

		public virtual int Status
		{
			get;
			set;
		}

		public virtual bool IsActive
		{
			get;
			set;
		}

	}
}

