//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using mds.BaseModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GridPage <T>: OperationResult<T>
{
	public virtual int CurrentPage
	{
		get;
		set;
	}

	public virtual int PageSize
	{
		get;
		set;
	}

	public virtual int TotalPage
	{
		get;
		set;
	}

	public virtual int Total
	{
		get;
		set;
	}

}

