//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace mds.BaseModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OperationMessage
	{
		public virtual string Message
		{
			get;
			set;
		}

		public virtual int Code
		{
			get;
			set;
		}

	}
}

