//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace mds.BaseModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class SolutionConfiguration : DataClassBase
	{
		public virtual Guid SolutionId
		{
			get;
			set;
		}

		public virtual string SolutionName
		{
			get;
			set;
		}

		public virtual int Version
		{
			get;
			set;
		}

		/// <summary>
		/// 是否将文件静态化储存
		/// </summary>
		public virtual bool IsFile
		{
			get;
			set;
		}

		public virtual string Content
		{
			get;
			set;
		}

		public virtual bool Enable
		{
			get;
			set;
		}

		/// <summary>
		/// 运行环境
		/// </summary>
		public virtual int Environment
		{
			get;
			set;
		}

		public virtual List<ComponentConfiguration> Components
		{
			get;
			set;
		}

		/// <summary>
		/// 配置模式是否远程化
		/// </summary>
		public virtual bool IsRemote
		{
			get;
			set;
		}

	}
}

