//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace mds.BaseModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;
    [DataContract]
    public class SolutionConfiguration : DataClassBase
    {
        [DataMember]
        public int ID { set; get; }
        [DataMember]
        public virtual Guid SolutionId
		{
			get;
			set;
		}
        [DataMember]
        public virtual string SolutionName
		{
			get;
			set;
		}
        /// <summary>
        /// 为0时就一直取最新的版本，配置版本号，改变一次配置内容自动递增
        /// </summary>
        [DataMember]
        public virtual int Version
		{
			get;
			set;
		}

        /// <summary>
        /// 是否将文件静态化储存
        /// </summary>
        [DataMember]
        public virtual bool IsFile
		{
			get;
			set;
		}
        [DataMember]
        public virtual string Content
		{
			get;
			set;
		}
        [DataMember]
        public virtual bool Enable
		{
			get;
			set;
		}

        /// <summary>
        /// 运行环境
        /// </summary>
        [DataMember]
        public virtual int Environment
		{
			get;
			set;
		}
        [DataMember]
        public virtual List<ComponentConfiguration> Components
		{
			get;
			set;
		}

        /// <summary>
        /// 配置模式是否远程化
        /// </summary>
        [DataMember]
        public virtual bool IsRemote
		{
			get;
			set;
		}

	}
}

